import streamlit as st
import joblib
import pandas as pd
import os


# --------------------------------------------------
# Page Configuration
# --------------------------------------------------

st.set_page_config(
    page_title="Dynamic Pricing RL",
    page_icon="💰",
    layout="wide"
)


# --------------------------------------------------
# Title
# --------------------------------------------------

st.title("💰 Dynamic Pricing using Reinforcement Learning")

st.write(
    "Interactive dashboard for analyzing pricing decisions "
    "generated by a trained Q-Learning agent."
)


# --------------------------------------------------
# Model Path
# --------------------------------------------------

MODEL_PATH = "reports/models/q_learning_agent.pkl"


# --------------------------------------------------
# Load Model
# --------------------------------------------------

@st.cache_resource
def load_model():

    if not os.path.exists(MODEL_PATH):
        return None

    return joblib.load(MODEL_PATH)


agent = load_model()


if agent is None:

    st.error(
        "Trained Q-Learning model not found."
    )

    st.stop()


st.success("Q-Learning model loaded successfully.")


# --------------------------------------------------
# Q-Table
# --------------------------------------------------

q_table = agent.q_table


st.subheader("Q-Table")

q_df = pd.DataFrame(
    q_table,
    columns=[
        "Decrease Price",
        "Keep Price",
        "Increase Price"
    ]
)

q_df.index.name = "State"

st.dataframe(
    q_df,
    use_container_width=True
)


# --------------------------------------------------
# Pricing Decisions
# --------------------------------------------------

st.subheader("Pricing Decisions")


decisions = []

action_names = {
    0: "Decrease Price",
    1: "Keep Price",
    2: "Increase Price"
}


for state in range(len(q_table)):

    action = int(q_table[state].argmax())

    decisions.append({
        "State": state,
        "Action": action,
        "Decision": action_names[action]
    })


decision_df = pd.DataFrame(decisions)


st.dataframe(
    decision_df,
    use_container_width=True
)


# --------------------------------------------------
# Decision Distribution
# --------------------------------------------------

st.subheader("Decision Distribution")


distribution = (
    decision_df["Decision"]
    .value_counts()
)


st.bar_chart(distribution)


# --------------------------------------------------
# Selected State
# --------------------------------------------------

st.subheader("Pricing Recommendation")


selected_state = st.slider(
    "Select Pricing State",
    min_value=0,
    max_value=len(q_table) - 1,
    value=0
)


selected_action = int(
    q_table[selected_state].argmax()
)


selected_decision = action_names[
    selected_action
]


st.metric(
    "Recommended Pricing Action",
    selected_decision
)


# --------------------------------------------------
# Q-Values
# --------------------------------------------------

st.write("Q-Values for Selected State")

selected_values = pd.DataFrame({
    "Action": [
        "Decrease Price",
        "Keep Price",
        "Increase Price"
    ],
    "Q-Value": q_table[selected_state]
})


st.dataframe(
    selected_values,
    use_container_width=True
)


# --------------------------------------------------
# Footer
# --------------------------------------------------

st.divider()

st.caption(
    "Dynamic Pricing System powered by Reinforcement Learning "
    "and Q-Learning."
)